import os
from moviepy.editor import ImageClip, AudioFileClip
import asyncio
import edge_tts

# ==========================================
# VITT WIRE: ZERO-COST VIDEO ASSEMBLY
# ==========================================

async def generate_voiceover():
    """Generates a professional broadcast voiceover for free."""
    # Read the script generated by vitt_research.py
    with open("daily_script.txt", "r", encoding="utf-8") as f:
        script = f.read()
    
    # Using a high-quality Indian-English neural voice for testing
    # We will switch this to your clone once aditya_voice.wav is uploaded
    communicate = edge_tts.Communicate(script, "en-IN-NeerjaNeural")
    await communicate.save("voiceover.mp3")

def create_final_video():
    """Merges the visual engine output with the voiceover."""
    # Loading the latest image from vitt_engine and the new audio
    audio = AudioFileClip("voiceover.mp3")
    # Using the generated image from your vitt_engine logic
    img = ImageClip("output_reels.png").set_duration(audio.duration)
    
    video = img.set_audio(audio)
    video.write_videofile("vitt_wire_broadcast.mp4", fps=24)

if __name__ == "__main__":
    asyncio.run(generate_voiceover())
    create_final_video()
